### ISSUE TITLE
Hello, Is anybody there?

### ISSUE THREAD

**Issue by mbvgua** [kamemia/panAfricanmovement#5]
Hi. I intended to build a similar website to this and suddenly came across your repo. Is this still active and if so are you open to collaboration?

**Comment by kamemia** [comment]
Hi, No.I'm not actively working on this repo.

**Comment by mbuguadouglas** [comment]
Oh. Okay. Thanks for letting me know

**Comment by kamemia** [comment]
Okay. Is there anything else you need before i close the issue?

**Comment by mbuguadouglas** [comment]
Not at the moment. Feel free to close the issue.

**Comment by kamemia** [comment]
Cool :thumbsup
